repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: no-commit-to-branch
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [--fail-under=80, --verbose, --generate-badge=./.github/badges, --badge-style=flat]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        additional_dependencies: ["toml"]
        args:
        -   --ignore=D107,D200,D203,D204,D212,D407
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports
-   repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: v0.32.2
    hooks:
        - id: markdownlint
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--exclude /tests]
