name: "TODO"
on: ["push"]
jobs:
  check-new-issues:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@main"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6.8"
        id: "todo"
